name: auto_merge

on:
  pull_request:
    branches: [ src ]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v2
      - name: ğŸ©¹ Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: patch
          github-token: ${{ secrets.GITHUB_TOKEN }}
